services:
  bot:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    restart: always
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=amazon_price_track
    ports:
      - "30531:5432"

volumes:
  postgres_data: