services:
  bot:
    build: .
    env_file:
      - .env
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=amazon_price_track
    ports:
      - 5432:5432

volumes:
  postgres_data:
